### ISSUE TITLE
Uncaught TypeError: elem.remoteObject

### ISSUE THREAD

**Issue by electrumguy** [Xetera/ghost-cursor#121]
I am getting this error:

```
Uncaught TypeError TypeError: elem.remoteObject is not a function
    at <anonymous> (...\node_modules\ghost-cursor\lib\spoof.js:483:61)
    at step (...\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at <anonymous> (...\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at fulfilled (...\node_modules\ghost-cursor\lib\spoof.js:16:58)
```

Sample code to regenerate:

`import { chromium } from 'playwright';
import { createCursor } from "ghost-cursor"

const example = (async () => {
        const browser = await chromium.launch({ headless: false });
        const page = await browser.newPage();
        const cursor = createCursor(page)
        await page.goto('https://www.example.com/')
        await cursor.click('body > div:nth-child(1) > p:nth-child(3) > a:nth-child(1)', { waitForClick: 10000, waitForSelector: 10000, paddingPercentage: 20 })
})();
`

Utilizing:
"@playwright/browser-chromium": "^1.41.2"
"ghost-cursor": "^1.2.0",

**Comment by Niek** [comment]
As stated, `ghost-cursor` is a library for puppeteer and not for playwright. It should be possible to add playwright support though, feel free to open a PR.

**Comment by unickq** [comment]
https://github.com/reaz1995/ghost-cursor-playwright

**Comment by sanchobouillant** [comment]
I have the same issue with 'puppeteer' when I use a locator.

```
    const testButton = await page.locator('button');
    await cursor.click(testButton);
```

```
TypeError: elem.remoteObject is not a function
    at Object.<anonymous> (node_modules/ghost-cursor/lib/spoof.js:521:61)
    at step (node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (node_modules/ghost-cursor/lib/spoof.js:25:53)
    at node_modules/ghost-cursor/lib/spoof.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/ghost-cursor/lib/spoof.js:15:12)
    at go (node_modules/ghost-cursor/lib/spoof.js:474:64)
    at Object.<anonymous> (node_modules/ghost-cursor/lib/spoof.js:579:50)
    at step (node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (node_modules/ghost-cursor/lib/spoof.js:25:53)
```
