### ISSUE TITLE
xPath not working

### ISSUE THREAD

**Issue by DmitryKvant** [Xetera/ghost-cursor#18]
`await cursor.click("//a[contains(., 'Поиск заказов')]")`
i get error
`TypeError: elem.boundingBox is not a function
    at Object.<anonymous> (/home/dmitrykvant/yandexservicebotpuppeteer/node_modules/ghost-cursor/lib/spoof.js:258:50)
    at step (/home/dmitrykvant/yandexservicebotpuppeteer/node_modules/ghost-cursor/lib/spoof.js:44:23)
    at Object.next (/home/dmitrykvant/yandexservicebotpuppeteer/node_modules/ghost-cursor/lib/spoof.js:25:53)
    at fulfilled (/home/dmitrykvant/yandexservicebotpuppeteer/node_modules/ghost-cursor/lib/spoof.js:16:58)
    at runMicrotasks (<anonymous>)
`

**Comment by DmitryKvant** [comment]
<img width="1030" alt="Снимок экрана 2021-01-07 в 00 09 18" src="https://user-images.githubusercontent.com/17162785/103790966-d4b91c00-507c-11eb-8b9a-0d1256c3021a.png">
Quick fix

**Comment by Niek** [comment]
This was fixed in https://github.com/Xetera/ghost-cursor/commit/ad91cf44fea2a2e476e83490c98108fcca3ab487

I will publish this soon as v1.0.7, in the meantime use `npm i Xetera/ghost-cursor#master`

**Comment by Niek** [comment]
Released as v1.1.0: https://www.npmjs.com/package/ghost-cursor
