### ISSUE TITLE
Quads Not Found over and over

### ISSUE THREAD

**Issue by lelly8484** [Xetera/ghost-cursor#86]
Sometimes it works sometimes it doesn't, when I make it click a div, then another div, it can't click the third div and keeps spamming this. What does it mean?

Quads not found, trying regular boundingBox
Falling back to JS scroll method ProtocolError: Protocol error (DOM.scrollIntoViewIfNeeded): Node does not have a layout object
    at C:\Users\xxx\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\Users\xxx\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at Object.<anonymous> (C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:480:75)
    at step (C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at Object.next (C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:15:12)
    at go (C:\Users\xxx\node_modules\ghost-cursor\lib\spoof.js:429:64)

**Comment by DaBossCoda** [comment]
Also having this issue. Did you manage to solve it?
