### ISSUE TITLE
cursor.click("#login") error

### ISSUE THREAD

**Issue by TonyChen-SH** [Xetera/ghost-cursor#91]
`
env:
nodejs v19.0.0
"ghost-cursor": "^1.1.16",   
"puppeteer": "^19.7.1",   
"puppeteer-extra": "^3.3.4",   
"puppeteer-extra-plugin-click-and-wait": "^2.3.2" 
`

`
C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\math.js:95
    return new (bezier_js_1.Bezier.bind.apply(bezier_js_1.Bezier, __spreadArray(__spreadArray([void 0, start], __read(anchors), false), [finish], false)))();
                                   ^

TypeError: Cannot read properties of undefined (reading 'bind')
    at bezierCurve (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\math.js:95:36)
    at path (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\spoof.js:229:40)
    at Object.<anonymous> (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\spoof.js:506:66)
    at step (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at Object.next (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at fulfilled (C:\Users\test\WebstormProjects\xxxxxx\node_modules\ghost-cursor\lib\spoof.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by Niek** [comment]
Can you share some sample code? This looks very strange.

**Comment by Niek** [comment]
I see something broke in `bezier-js@6.1.2` that was released 2 days ago. I have pinned the `bezier-js` dependency to `6.1.0` now and released this as `ghost-cursor@1.1.17`.

**Comment by TonyChen-SH** [comment]
> I see something broke in `bezier-js@6.1.2` that was released 2 days ago. I have pinned the `bezier-js` dependency to `6.1.0` now and released this as `ghost-cursor@1.1.17`.

thank u very much.

**Comment by Niek** [comment]
Reference: https://github.com/Pomax/bezierjs/issues/193

**Comment by visgotti** [comment]
I'm getting this issue on ghost-cursor@1.1.18 any ideas why?

**Comment by Niek** [comment]
> I'm getting this issue on ghost-cursor@1.1.18 any ideas why?

Check your version of `bezier-js`, it should be `v6.1.3`.

**Comment by visgotti** [comment]
It is, node v14.16.1

**Comment by visgotti** [comment]
bumping my node version fixed it but I rather not have to change it everywhere
